# Generated by Django 3.2.5 on 2021-08-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanforms',
            name='credit_approve',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanforms',
            name='form_status',
            field=models.CharField(default='false', max_length=255),
        ),
        migrations.AlterField(
            model_name='loanforms',
            name='sales_approve',
            field=models.CharField(default='false', max_length=50),
        ),
    ]
