# Generated by Django 3.2.5 on 2021-08-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loanforms_pan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanforms',
            name='pan_status',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pan_status',
            field=models.CharField(default='not_chked', max_length=255),
        ),
    ]
