# Generated by Django 3.2.5 on 2021-08-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210823_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanforms',
            name='file_name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
