# Generated by Django 3.2.5 on 2021-09-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loanforms_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanforms',
            name='enach_status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loanforms',
            name='subId',
            field=models.CharField(default='', max_length=255),
        ),
    ]
