# Generated by Django 3.2.5 on 2021-09-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210901_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanforms',
            name='applicant_bank_acc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loanforms',
            name='applicant_ifsc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
