# Generated by Django 3.2.5 on 2021-09-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210902_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanforms',
            name='coapp_ban_acc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loanforms',
            name='coapp_ifsc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
