# Generated by Django 3.2.5 on 2021-09-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210902_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanforms',
            name='esignId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='loanforms',
            name='esign_status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
